version: '3.1'
services:
  # app:
  #   container_name: fastify-app
  #   restart: always
  #   build: .
  #   image: 'fastify-app:1.0.0'
  #   ports:
  #     - '3000:3000'
  #   expose:
  #     - '3000'
  #   links:
  #     - mongodb
  mongodb:
    image: 'mongo:latest'
    restart: always
    container_name: fastify-app-mongodb
    ports:
      - '27017:27017'
    expose:
      - '27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: baedal
    volumes:
      - ./mongodb-data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      

